name = "Discord"
uuid = "91c305b0-c482-11e8-244f-23e78ed5e04c"
authors = ["PurgePJ <sindur.esl@gmail.com>, Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OpenTrick = "102dff8d-99cb-5cc2-9bf9-d9fe3a2e5e7a"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
TimeToLive = "37f0c46e-897f-50ef-b453-b26c3eed3d6c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
